config/routes.rb
Xmltojson::Application.routes.draw do
  get "convert/index"
  get "convert/cssinline"
  get "convert/pdf"
  post "convert/download_pdf"
  post "convert/index"
  post "convert/download_cssinline"

  get "convert/down"
  get "convert/api"
  root :to => "convert#index"

namespace :api do
  namespace :v1 do
    resources :xmltojson, :only=>[:create]
  end
end

end

app/models/convert.rb
class Convert < ActiveRecord::Base
  attr_accessible :file

end

app/controllers/api/v1/xmltojson_controller.rb
class Api::V1::XmltojsonController < ApplicationController

	def create
		render :json=> Hash.from_xml(params[:xml]).to_json
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/convert_controller.rb
#require 'premailer'
class ConvertController < ApplicationController
  layout "layconvert"
  def index
	  return if params[:converts].blank?

	  #@attachment = Convert.new
	  require 'json'
	  require 'digest'

	  @file = params[:converts].tempfile.path
	  @file_destino = Digest::MD5.hexdigest(params[:converts].original_filename.to_s) + ".json"
	  
	  File.open("public/xml/"+ @file_destino, 'w') {|f| f.write(Hash.from_xml(File.open(@file)).to_json)}

	  session[:file] = @file_destino
	  render :template => "convert/down"
  end


  def down
  	require 'open-uri'
	url = 'public/xml/' + session[:file]
	data = open(url).read
	send_data data, :disposition => 'attachment', :filename=> session[:file]
  end

  def api
  	
  end

  def cssinline

  end

  def pdf 
    
  end

  def download_pdf 
    file = Tempfile.new('foo')
    `wkhtmltopdf #{params[:url]} #{file.path}`
    send_file file.path, :x_sendfile => true, :type => 'pdf', :filename=>"converted.pdf"
  end

  def download_cssinline
  	#'http://eitamah.coredigital.com.br/public_html/cupons/para-impressao/060812469669AE02A86'
  	premailer = Premailer.new(params[:url], :warn_level => Premailer::Warnings::SAFE)
  	file = Tempfile.new('foo')
  	file.write premailer.to_inline_css
  	file.rewind
  	file.read      # => "hello world"
  	file.close

  	send_file file.path, :x_sendfile => true, :type => 'html', :filename=>"converted.html"
  end
end

app/helpers/api/v1/xmltojson_helper.rb
module Api::V1::XmltojsonHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/convert_helper.rb
module ConvertHelper
end

app/views/convert/api.html.erb
<h1>Api XmltoJson</h1>
<p>Este é um simples webservice para integrar ao XmltoJson.</p>

<ul class="endpoints" id="user_endpoint_list" style="">
	<li class="endpoint">
	    <ul class="operations">
	      <li class="get operation">
	            <div class="heading">
	                <h3>
	                  <span class="http_method">
	                    <a href="#" class="toggleOperation">POST</a>
	                  </span>
	                  <span class="path">
	                    <a href="#" class="toggleOperation">/api/v1/xmltojson?xml=xml</a>
	                  </span>
	                </h3>
	            </div>
	        </li>
	    </ul>
	<li>
</ul>

app/views/convert/cssinline.html.erb
<h1>HTML to CSS inline</h1>
<%= form_tag(convert_download_cssinline_path, multipart: true) do %>
  <%= text_field_tag 'url', "", class: "input-xxlarge",  title: "Enviar XML", placeholder: 'URL do HTML. Ex: http://google.com.br'%>
  <%= submit_tag "Converter", class: 'btn btn-primary' %>
<% end %>
<p>Transforme o seu HTML para o HTML com códigos CSS inline.</p>

app/views/convert/down.html.erb
<h1>Download to Json</h1>
<%= link_to "Baixar Json", convert_down_url %>

app/views/convert/index.html.erb
<h1>Convert to Json</h1>
<%= form_tag('index', multipart: true) do %>
  <%= file_field_tag 'converts', class: "input-small",  title: "Enviar XML" %>
  <%= submit_tag "upload", class: 'btn btn-primary' %>
<% end %>
<p>Coverta seus arquivos XML para Json. Basta fazer o upload do seu xml e faça o download totalmente
   convertido em Json.</p>

app/views/convert/pdf.html.erb
<h1>HTML to PDF</h1>
<%= form_tag(convert_download_pdf_path, multipart: true) do %>
  <%= text_field_tag 'url', "", class: "input-xxlarge",  title: "Enviar XML", placeholder: 'URL do HTML. Ex: http://google.com.br'%>
  <%= submit_tag "Converter", class: 'btn btn-primary' %>
<% end %>
<p>Transforme o seu HTML para o PDF.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Conversores</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/layconvert.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Xmltojson" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <link href='http://fonts.googleapis.com/css?family=Cabin+Condensed' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "api", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Converters</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "XML to JSON", convert_index_url  %></li>
              <li><%= link_to "HTML to Inline CSS", convert_cssinline_url  %></li>
              <li><%= link_to "HTML to PDF", convert_pdf_url  %></li>
              <li><%= link_to "Api", convert_api_url  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Autores</h3>
                <h4><%= link_to "Italo Matos", "https://bitbucket.org/italomatos", target: "_black" %></h4>
                <h4><%= link_to "Frankyston Lins", "https://bitbucket.org/frankystonlins", target: "_black" %></h4>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company <%= link_to "Core Digital", "http://www.coredigital.com.br" %></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "bootstrap.file-input" %>

    
    <script>
      $(function() {
        $('input[type=file]').bootstrapFileInput();
      });
    </script>

  </body>
</html>